const { GoogleGenAI, Behavior } = require("@google/genai");
const { z } = require('zod')
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
});

const interviewReoprtScheme = z.object({

    matchScore: z.number().describe("match score between resume and job description"),
    technicalQuestion: z.array(z.object({
        question: z.string().describe("The technical question can be asked in interview based on resume and job description"),
        intention: z.string().describe("the intention of the interviewer behind asking this question or what the interviewer want to check"),
        answer: z.string().describe("how to answer this question, what point to cover, what approach to take")
    })).describe("Technical question that can be asked in interview based on resume and job description"),
    behaviouralQuestion: z.array(z.object({
        question: z.string().describe("The behavioural question can be asked in interview based on resume and job description"),
        intention: z.string().describe("the intention of the interviewer behind asking this question or what the interviewer want to check"),
        answer: z.string().describe("how to answer this question, what point to cover, what approach to take")
    })).describe("Behavioural question that can be asked in interview based on resume and job description"),
    skillGap: z.array(z.object({
        skill: z.string().describe("The skill which candidate is lacking"),
        severity: z.enum(["low", "medium", "high"]).describe("the severity of laking skill")
    })).describe("Lkist of skill gaps in candidate based on resume and job description"),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day of preparation"),
        focus: z.string().describe("The focus of preparation"),
        task: z.array(z.string()).describe("The task to be done on that day")
    })).describe("Preparation plan for the interview"),
    title: z.string().describe("The title of the job fro which interview report is generated"),

})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `Generate the interview Report according to the information provided by user. 
    Resume: ${resume}
    Self Description: ${selfDescription}
    Job Description: ${jobDescription}`

    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: z.toJSONSchema(interviewReoprtScheme)
        }
    })

    return JSON.parse(response.text)
}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: z.toJSONSchema(resumePdfSchema),
        }
    })


    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer

}

module.exports = { generateInterviewReport, generateResumePdf }